### ISSUE TITLE
API Coverage Tracking

### ISSUE THREAD

**Issue by jeremylow** [bear/python-twitter#342]
Some of these may be out of scope or just not a good fit for the API, but the following endpoints aren't supported at the moment:

- [ ] `account/remove_profile_banner`
- [ ] `account/settings`
- [ ] `account/settings`
- [ ] `collections/:id/content`
- [ ] `collections/create`
- [ ] `collections/destroy`
- [ ] `collections/entries`
- [ ] `collections/entries/add`
- [ ] `collections/entries/curate`
- [ ] `collections/entries/move`
- [ ] `collections/entries/remove`
- [ ] `collections/list`
- [ ] `collections/show`
- [ ] `collections/update`
- [ ] `direct_messages`
- [ ] `direct_messages/show`
- [ ] `friendships/no_retweets/ids`
- [ ] `geo/id/:place_id`
- [ ] `geo/place`
- [ ] `geo/reverse_geocode`
- [ ] `geo/search`
- [ ] `help/languages`
- [ ] `help/privacy`
- [ ] `help/tos`
- [ ] `lists/members/show`
- [ ] `lists/show`
- [ ] `lists/subscribers`
- [ ] `lists/update`
- [ ] `projects`
- [ ] `projects/:id`
- [ ] `saved_searches/create`
- [ ] `saved_searches/destroy/:id`
- [ ] `saved_searches/list`
- [ ] `saved_searches/show/:id`
- [ ] `statuses/lookup`
- [ ] `statuses/show/:id`
- [ ] `streams/:id/content`
- [ ] `streams/:id/metrics`
- [ ] `streams/:id/trendline`
- [ ] `streams/compare`
- [ ] `streams/compare_to_target`
- [ ] `trends/available`
- [ ] `trends/closest`
- [ ] `users/profile_banner`
- [ ] `users/report_spam`
- [ ] `users/suggestions/:slug/members`

**Comment by jeremylow** [comment]
(This is across the following API domains: Media, Collections, TON, Curator, REST; does not include Ads API.)

**Comment by bear** [comment]
great list! I've done a couple passes like this in the past and it's both amazing and depression :)

Do we want to flag them as yes, no, maybe and group them into each their own issue?

**Comment by jeremylow** [comment]
Thanks! Yeah, there's a little bit of work to be done, no? I've redone the list a bit with the API type as the heading. For Collections, I don't have access for any of my apps, but I've emailed Twitter to see if that's possible. 

As for organizing, maybe just comment as to what folks want to take on and then open issues as they come up? It'd be nice if there were a way for people to check off what they want to/are working on, but this is just markdown, alas...

I've gone through and to my mind, I think the only ones where I'd say not include (at least on a first pass) are `GET /help/privacy` and `GET /help/tos`, but that's anyone's call as to whether it'd be useful for them.

**Comment by jeremylow** [comment]
OK, so I started a new branch for this stuff. It's ``feature/api_coverage``. I think I still have test data for the two direct messages endpoints and the lists endpoints, so I'll work on those this week.
